baseURL = "http://example.org/"
languageCode = "en-us"
title = "Lover of Travel"
metaDataFormat = "yaml"

[params]
  customCSS = ["/css/global.css", "/css/header.css", "/css/home.css", "/css/blog-post.css", "css/contact.css"]
  customJS = ["/js/header.js"]


# Feature Image Dimesions: 1440x756

# [[menu.main]]
#   name = "Home"
#   url = "/"

# [[menu.main]]
#   name = "About"
#   url = "/about"

# [[menu.main]]
#   name = "Contact"
#   url = "/contact"