baseURL = "http://example.org/"
languageCode = "en-us"
title = "Lover of Travel"
metaDataFormat = "yaml"

[params]
  customCSS = ["/css/global.css", "/css/header.css", "/css/home.css", "/css/blog-post.css", "css/contact.css"]
  customJS = ["/js/header.js"]


# Feature Image Dimesions: 1440x756
# [menu]

#   [[menu.main]]
#     name = "Home"
#     title = "Home Page"
#     url = "/"
#     weight = 1

#   [[menu.main]]
#     name = "About"
#     title = "About Page"
#     url = "/about"
#     weight = 2

#   [[menu.main]]
#     name = "Contact"
#     title = "Contact Page"
#     url = "/contact"
#     weight = 3